-- Superseded by supabase/migrations/004_ohlc_cache.sql, which is the
-- tracked authoritative definition (creates the table in both public and
-- test schemas with grants). This file is kept as a historical artifact;
-- do not apply it.
